### ISSUE TITLE
CI workflow failure

### ISSUE THREAD

**Issue by ganymedio** [movement-network/movement-hack#64]
Error is 

```
Run ./bin/maintainer/citest.sh
  ./bin/maintainer/citest.sh
  shell: sh -e {0}
/__w/_temp/c9b0da90-5374-43ec-af1d-8607[2](https://github.com/movementlabsxyz/movement-hack-old/actions/runs/9546387234/job/26309145402#step:3:2)3d77944.sh: 1: ./bin/maintainer/citest.sh: not found
Error: Process completed with exit code 127.
```

Any idea why that's happening or how to fix it?

I do see the file `/bin/maintainer/citest.sh` in the repo.

Here's the workflow in `citest.yaml`:

```
name: Run Citests

on:
  push:
    branches:
      - main
jobs:       
  test:
      runs-on: ubuntu-latest
      container:
        image: mvlbs/m1:latest
      steps:
        - run: ./bin/maintainer/citest.sh
```

and here's the `Dockerfile`:

```
FROM public.ecr.aws/c4i6k4r8/movement-dev:latest

COPY . .

ENTRYPOINT ["/bin/bash", "./abin/citest.sh"]
```

Could it be that `https://public.ecr.aws/c4i6k4r8/movement-dev:latest` or the image `mvlbs/m1:latest` needs to be updated?
